name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  docs-publish:
    name: publish documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc

      - name: Build documentation
        run: hatch run mkdocs gh-deploy --force
